### ISSUE TITLE
[question] What is the diference in b43-fwcuter and this b43-tools?

### ISSUE THREAD

**Issue by jristz** [mbuesch/b43-tools#2]
the webpage http://bues.ch/cms/hacking/misc.html sound like those two are the same progect with different repositories or names. and here no have a READMe or anothing that clearly show the difference in both, or if one is preffered over the other.

pleas clarify this or show me the light.

**Comment by mbuesch** [comment]
There is no difference. It's the same thing.
The b43-tools collection contains b43-fwcutter, among other b43 related tools.
